// Generated by CoffeeScript 1.3.1
(function() {

  window.plugins.broadcast = {
    emit: function(div, item) {
      $("head").append($("<link rel='stylesheet' href=\"http://localhost:1986/lib/bootstrap/css/bootstrap.css\" type=\"text/css\" />"));
      $("head").append($("<link href=\"lib/bootstrap/css/bootstrap-responsive.css\" rel=\"stylesheet>"));
      $("head").append($("<link href=\"theme/granite.css\" rel=\"stylesheet>"));
      $("head").append($("<link href=\"broadcast.css\" rel=\"stylesheet>"));
      $.getScript('http://localhost:1986/broadcast.js', function(data, textStatus, jqxhr) {
        broadcast.url = 'http://localhost:1986';
        $('head').append($('<link href="' + broadcast.url + '/lib/bootstrap/css/bootstrap.css" rel="stylesheet" />'));
        $('head').append($('<link href="' + broadcast.url + '/lib/bootstrap/css/bootstrap-responsive.css" rel="stylesheet" />'));
        $('head').append($('<link href="' + broadcast.url + '/broadcast.css" rel="stylesheet>'));
        $.getScript(broadcast.url + '/socket.io/socket.io.js');
        $.getScript(broadcast.url + '/lib/bootstrap/js/bootstrap.min.js');
        $.getScript(broadcast.url + '/util.js');
        $.getScript(broadcast.url + '/view.js');
        return $.getScript(broadcast.url + '/controller.js');
      });
      return div.append("<img alt=\"Wildhorse Lake\" src=\"http://localhost:1986/test.png\" /> <br/>\nnot in a paragraph\n<p>\n  In a paragraph.\n</p>      \n\n<!-- online accordion -->\n<div class=\"accordion\" id=\"broadcast-online\">\n  <div class=\"accordion-group\" id=\"broadcast-online-tmpl\">\n    Retrieving data from server...\n  </div>\n</div>\n\n<!-- broadcasts accordion -->\n<div class=\"accordion\" id=\"broadcasts\"></div> ");
    },
    bind: function(div, item) {
      return console.log('i bound something');
    }
  };

}).call(this);
