// Generated by CoffeeScript 1.3.1
(function() {

  window.plugins.broadcast = {
    emit: function(div, item) {
      $('head').append($('<link href="http://localhost:1986/broadcast.css" rel="stylesheet">'));
      $.getScript('http://localhost:1986/broadcast.js');
      return div.append("<div class=\"accordion\" id=\"broadcast-online\">\n  <div class=\"accordion-group\" id=\"broadcast-online-tmpl\">\n    Retrieving data from server...\n  </div>\n</div>\n<div class=\"accordion\" id=\"broadcasts\"></div> ");
    },
    bind: function(div, item) {
      return console.log('i bound something');
    }
  };

}).call(this);
